#!/usr/bin/env python
# coding:utf-8
from tendo import singleton
singleton.SingleInstance()  # will sys.exit(-1) if other instance is running

from monitor_plim import monitor_plim_init
from monitor import MONITOR


def main():
    monitor_plim_init()

if __name__ == '__main__':
    main()
    import sys
    if sys.argv[1:] and sys.argv[1] == '-once':
        pass
    else:
        MONITOR.run()
